"""added url into article

Revision ID: 17921c7e08a1
Revises: 7deddb28d0ca
Create Date: 2018-08-28 06:02:09.794030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17921c7e08a1'
down_revision = '7deddb28d0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'url')
    # ### end Alembic commands ###
