"""empty message

Revision ID: 321c84b91340
Revises: d9562eb2311e
Create Date: 2018-08-15 09:44:39.235407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '321c84b91340'
down_revision = 'd9562eb2311e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hero_name', table_name='hero')
    op.drop_table('hero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_index('ix_hero_name', 'hero', ['name'], unique=True)
    # ### end Alembic commands ###
