"""empty message

Revision ID: 8b1d273be38e
Revises: 9413c8990be0
Create Date: 2018-07-11 17:40:35.705781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1d273be38e'
down_revision = '9413c8990be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_name'), 'area', ['name'], unique=True)
    op.add_column(u'supermarket', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'supermarket', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supermarket', type_='foreignkey')
    op.drop_column(u'supermarket', 'area_id')
    op.drop_index(op.f('ix_area_name'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
