"""empty message

Revision ID: d9562eb2311e
Revises: 8b1d273be38e
Create Date: 2018-08-08 06:54:31.166511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9562eb2311e'
down_revision = '8b1d273be38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('sub_category_id', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('supermarket_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article', 'supermarket', ['supermarket_id'], ['id'])
    op.create_foreign_key(None, 'article', 'sub_category', ['sub_category_id'], ['id'])
    op.create_foreign_key(None, 'article', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'supermarket_id')
    op.drop_column('article', 'sub_category_id')
    op.drop_column('article', 'category_id')
    # ### end Alembic commands ###
